env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'eslint:recommended'
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 1
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/prefer-interface': 0
  '@typescript-eslint/explicit-function-return-type':
    - 1
    - allowExpressions: true
      allowTypedFunctionExpressions: true
  '@typescript-eslint/no-unused-vars':
    - 1
    - argsIgnorePattern: ^_|ignore
      varsIgnorePattern: ^_|ignore
      ignoreRestSiblings: true
  no-unused-vars: 0
